name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  https:
    name: Ensure no-TLS snapshot usage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Ensure http://snapshot.debian.org (https://github.com/debuerreotype/debuerreotype/pull/119#issuecomment-901457009)
        run: |
          rm .github/workflows/ci.yml # this file itself will always be a match, but it's the only valid one 👀
          if grep -rn 'https://snapshot.debian.org'; then
            exit 1
          fi

  image:
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.build.outputs.metadata }}
    steps:
      - name: Checkout Debuerreotype
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: '.'
          outputs: type=docker,dest=/tmp/debuerreotype.tar
          tags: local/debuerreotype:latest

      - name: Upload debuerreotype image tarball
        uses: actions/upload-artifact@v4
        with:
          name: debuerreotype
          path: /tmp/debuerreotype.tar

  test:
    needs:
      - image
    strategy:
      matrix:
        include:
          - { SUITE: stable,    CODENAME: jessie,  TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: c099dbc9579aff85ad118e3bfcf850b9ddea73ad69525711c52e2bd28030186c }
          - { SUITE: jessie,    CODENAME: "",      TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: c099dbc9579aff85ad118e3bfcf850b9ddea73ad69525711c52e2bd28030186c }
          - { SUITE: testing,   CODENAME: stretch, TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: 0549fb820e8cbefda22fc72a3607f4a7ead622bfc2fd1f047caac0692d3239e5 }
          - { SUITE: stretch,   CODENAME: "",      TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: 0549fb820e8cbefda22fc72a3607f4a7ead622bfc2fd1f047caac0692d3239e5 }
          - { SUITE: unstable,  CODENAME: sid,     TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: b3fe1c7f347ad60739084ca9b8349f43eeffe6533291a81736174cc9d19d194d }
          - { SUITE: sid,       CODENAME: "",      TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: b3fe1c7f347ad60739084ca9b8349f43eeffe6533291a81736174cc9d19d194d }
          - { SUITE: oldstable, CODENAME: wheezy,  TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: ad4e0014b058af4d33476156190794dd3f13f07c3530fbc8eaab677cf10aaa50 }
          - { SUITE: wheezy,    CODENAME: "",      TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: ad4e0014b058af4d33476156190794dd3f13f07c3530fbc8eaab677cf10aaa50 }

          # EOL suites testing
          - { SUITE: eol, CODENAME: etch,  TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: 8210bd151b21d785e0c0674152d6c506b5e4dca66b445ffefac43144c2e97d30 }
          - { SUITE: eol, CODENAME: lenny, TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: fd3adf5e8a72784d42f4974bf188fc0adf78b89fdd5234e2df38fb8151e70b31 }
          - { SUITE: eol, CODENAME: woody, ARCH: i386, TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: fc26d66a510fec2140859bfa9e85016b61231de2fe70287ce0c1a474e5b721cc }
          - { SUITE: eol, CODENAME: jessie, TIMESTAMP: "2021-03-01T00:00:00Z", SHA256: 7e89b60c07dbab9b331ee9e6390deb3d88e98af673b89b0711066a6a1865defb }

          # deb822 / usr-is-merged testing
          - { SUITE: unstable, CODENAME: "", TIMESTAMP: "2022-09-30T00:00:00Z", SHA256: 16cb8ae5f2bb6c08627172b2a64027478aa6dd78b588fc6a4b3fcc59338e448a }
          - { SUITE: bookworm, CODENAME: "", TIMESTAMP: "2022-09-30T00:00:00Z", SHA256: 44854026cc9e52f902171b9e40d96f448e72043ae1f6d7f9a3cc710c536aa666 }
          - { SUITE: bullseye, CODENAME: "", TIMESTAMP: "2022-09-30T00:00:00Z", SHA256: 761b6b66c7e1d9e0fa10c2578a4258fa6ff5c473931a2346b8cf75404b666469 }

          # qemu-debootstrap testing
          - { ARCH: arm64,   SUITE: jessie,   CODENAME: "", TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: ebe6aa294a28caefd0acc5b42fc60e4ab8cc9c03fb6d2184b48cb2f1084b5e66 }
          - { ARCH: sh4,     SUITE: unstable, CODENAME: "", TIMESTAMP: "2022-02-01T00:00:00Z", SHA256: 2fd0500e00299622fc568783d4f19f44a26921ecc9ea9d2ba4d9f152e90c169e }
          - { ARCH: riscv64, SUITE: unstable, CODENAME: "", TIMESTAMP: "2022-02-01T00:00:00Z", SHA256: 658ca6bd3c6174b3876a18fbe4b08dcdbb865f94e54b29458485ca75b20dda49 }

          # a few entries for "today" to try and catch issues like https://github.com/debuerreotype/debuerreotype/issues/41 sooner
          - { SUITE: unstable,  CODENAME: "", TIMESTAMP: "today 00:00:00", SHA256: "" }
          - { SUITE: stable,    CODENAME: "", TIMESTAMP: "today 00:00:00", SHA256: "" }
          - { SUITE: oldstable, CODENAME: "", TIMESTAMP: "today 00:00:00", SHA256: "" }

          # Dockerfile checksums
          - { DISTRO: dockerfile, SUITE: stretch, TIMESTAMP: "2017-05-08T00:00:00Z", SHA256: 7b295f07692e13e3aaec0709e38f5fbfe3b7153d024c556430be70fd845fc174 }
          - { DISTRO: dockerfile, SUITE: jessie,  TIMESTAMP: "2017-05-08T00:00:00Z", SHA256: 5d1daeb8e817a56d28b65b4fa5eb09ebb1963299a0ccfd2a37c07560779653cd }
          # README.md checksum
          - { DISTRO: readme,     SUITE: stretch, TIMESTAMP: "2017-01-01T00:00:00Z", SHA256: ac026b83d085e1e516e21865a92c443529119264a302bcefc60f0a8613e922ad }

          - { DISTRO: ubuntu, SUITE: eol, CODENAME: breezy }
          - { DISTRO: ubuntu, SUITE: eol, CODENAME: gutsy }
          - { DISTRO: ubuntu, SUITE: bionic }
          - { DISTRO: ubuntu, SUITE: eol, CODENAME: cosmic, ARCH: armhf }
          - { DISTRO: ubuntu, SUITE: focal }
          - { DISTRO: ubuntu, SUITE: focal, ARCH: i386 }
          - { DISTRO: ubuntu, SUITE: jammy }
          - { DISTRO: ubuntu, SUITE: noble }
          - { DISTRO: ubuntu, SUITE: questing, ARCH: amd64v3 }
      fail-fast: false
    name: Test ${{ matrix.DISTRO && format('{0} ', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format(' ({0})', matrix.CODENAME) }}${{ matrix.ARCH && format(' [{0}]', matrix.ARCH) }}${{ matrix.TIMESTAMP && format(' at {0}', matrix.TIMESTAMP) }}
    runs-on: ubuntu-24.04
    env: ${{ matrix }}
    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
      - name: Download debuerreotype image tarball
        uses: actions/download-artifact@v4
        with:
          name: debuerreotype
          path: /tmp
      - name: Load debuerreotype image
        run: docker load --input /tmp/debuerreotype.tar

      - name: Prepare Environment
        run: |
          if [ -n "${ARCH:-}" ]; then
            sudo apt-get update -qq
            sudo apt-get install -yqq binfmt-support qemu-user-static
          fi
          docker run -d --name squignix --restart always tianon/squignix
          git clone --depth 1 https://github.com/tianon/pgp-happy-eyeballs.git ~/phe
          ~/phe/hack-my-builds.sh
          rm -rf ~/phe

      - name: Build
        env:
          IMAGE: ${{ fromJSON(needs.image.outputs.metadata)['image.name'] }}
        run: |
          "./.validate-${DISTRO:-debian}.sh"
